### ISSUE TITLE
SVG data URI might be larger than necessary

### ISSUE THREAD

**Issue by bfred-it** [filamentgroup/directory-encoder#18]
I noticed that the SVG encoder builds a proper URL but apparently browsers don't need that. From my (quick) tests it appears that we only really need to remove [linebreaks](https://github.com/svg/svgo/blob/master/plugins/cleanupAttrs.js) and to escape quotation marks: `\"`

* directory-encoder output: [JS Bin](http://jsbin.com/nifobuqefu/1/edit?css,output)
* Custom output (20% lighter): [JS Bin](http://jsbin.com/ruvuhudozo/1/edit?css,output), [CSS validator](http://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fjsbin.com%2Fruvuhudozo%2F1.css&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en)

--

Also I'm not sure why it's set to create URIs with `charset=US-ASCII` instead of UTF-8

**Comment by jefflembeck** [comment]
@bfred-it - all non-base64 data uris use US-ASCII - it's part of the spec, so we need to adhere to that to make sure it will work across browsers and in future browsers.

Relevant specs - https://tools.ietf.org/html/rfc1738 & https://tools.ietf.org/html/rfc2397

Since we're following the spec, we also make sure that the data uri is encoded as a proper uri, since we're building a pretty universal tool and want to be sure that there are no unexpected errors on our part.

All of that being said, when comparing a gzipped version of the above svg css files, there is a 3% difference. While I'm normally the type of person who watches bytes used very closely, a 3% difference is absolutely worth it for me in order to maintain correctness and adherence to the specification.

Thank you for taking time to test this stuff and to flag an issue!

**Comment by bfred-it** [comment]
Duh, specs of course! It makes sense! And +1 for the showing that there's just a 3% difference. That's manageable :)
