### ISSUE TITLE
Allow files in subfolder to be passed in?

### ISSUE THREAD

**Issue by zigotica** [filamentgroup/directory-encoder#24]
Hi,

I would like to make grunticon use groups of icons arranged in subfolders. Currently not possible (afaik) due to directory-encoder. Would it make sense for you to add this enhancement?

Thanks

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/filamentgroup/directory-encoder/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!
