### ISSUE TITLE
Support for multiple of the same file, with different names

### ISSUE THREAD

**Issue by jefflembeck** [filamentgroup/directory-encoder#4]
Originally here: https://github.com/filamentgroup/grunticon/issues/45

Let's say there are two svgs that have the exact same content, and they are named bear.svg and holycraphugemammal.svg

Instead of the output being:

```
.icon-bear {
  // css stuff
}

.icon-holycraphugemammal {
  // same css stuff that was inside bear
}
```

We should be able to do:

```
.icon-bear,
.icon-holycraphugemammal {
  // css stuff
}
```

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/filamentgroup/directory-encoder/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!
