### ISSUE TITLE
Add ability to generate sprite sheet

### ISSUE THREAD

**Issue by jefflembeck** [filamentgroup/directory-encoder#9]
Currently nopngencode will allow the css generated to link directly to a specific file.

I'd like to see an entire folder turned into a sprite and then the css generated attach to that.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/filamentgroup/directory-encoder/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!
